@startuml
'https://plantuml.com/class-diagram

-class TodoItem {
    -String : itemName
    -Date : dueDate
    -String : itemDescription
    -flag : CheckBox
    +TodoItem(itemName, dueDate, itemDescription)
    +setItemName(itemName)
    +setDueDate(dueDate)
    +setDescription(itemDescription)
    +setFlag(flag)

    +getItemName() : String
    +getItemDescription() : String
    +getFlag() : CheckBox
    +getDueDate() : String
    +compare(TodoItem) : boolean
}
  TodoList o--> TodoItem
  TodoController o--> TodoList


+class TodoList {
    -todoList : ObservableList<TodoItem> :
    -fileName : String

    +TodoList(inputList, fileName)
    +get(itemID) : TodoItem
    +add(todoName, todoDate, todoDesc)
    +addTodoItem(TodoItem)
    +changeFlag(index)
    +delete(itemID)
    +editFileName(name)
    +deleteList()
    +printToFile()
    +add(todoName, todoDate, todoDesc)
    +editName(index, todoName)
    +editDate(index, todoDate)
    +editDesc(index, todoDesc)
    +getTodoList() : ObservableList<TodoItem>
    +getFileName() : String
    +getCompletedFlags() : ObservableList<TodoItem>
    +getUncompletedFlags() : ObservableList<TodoItem>
    +clearList()
    +printToFile()
    +readData()
    +search()
    -inputData()

}


+class TodoController implements Initializable {
    -todoList : TodoList
    -flag : int
    -addButton : Button
    -deleteButton : Button
    -inputDate : TextField
    -inputDesc : TextField
    -inputName : TextField
    -table : TableView<TodoItem>
    -todoDate : TableColumn<TodoItem, String>
    -TodoDesc : TableColumn<TodoItem, String>
    -todoFlag : TableColumn<TodoItem, Boolean>
    -todoItem : TableColumn<TodoItem, String>
    -completedItems : MenuItem
    -clearList : MenuItem
    -viewAll : MenuItem
    -uncompletedItems : MenuItem
    +handleClearList()
    +handleCompletedFlags()
    +handleAddButton()
    +handleViewAll()
    +handleDeleteButton()
    +handleUncompletedFlags()
    +handleExportList()
    +handleSearchButton()
    +setTable(todoList)
    +initialize(URL location, ResourceBundle resources)

    +setUpItem()
    +setUpDate()
    +setUpDesc()
    +setUpFlag()
    -updateState()
    -popupError()

    +handleTextChange()
    +modifyElement()
}
Interface Initializable
note left: JavaFX Interface



@enduml